name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Installation depends
      run: |
        pip install tensorflow_datasets
        python3 main.py
        zip -r dataset.zip ~/tensorflow_datasets

    - name : upload binary
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Task
        path: ./output.zip
