name: cross
on: push

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory
      - name: cross
        run: |
          git clone https://github.com/helix-editor/helix.git
          cargo install cross
          cd helix && cross build --release --target aarch64-unknown-linux-musl

#       - name : upload binary
#         uses: actions/upload-artifact@master
#         if: always()
#         with:
#           name: Task
#           path: ./dataset.zip
