name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Installation depends
      run: |
        export AWS_REGION="eu-west-1"
        aws --version
        mkdir output
        aws s3 cp s3://msd-for-monai-eu/Task01_BrainTumour.tar --no-sign-request ./output
        zip -r output.zip ./output
#        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#        unzip awscliv2.zip
#        sudo ./aws/install

        
    - name : upload binary
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Task
        path: ./output.zip
