name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Installation depends
      run: |
        pip install tensorflow tensorflow_datasets
        python3 main.py
        7z a dataset.zip ~/tensorflow_datasets/glue

    - name : upload binary
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Task
        path: ./dataset.zip
